// Generated by CoffeeScript 1.10.0
var Chalk, babel, coffee, coffeeToJs, gulp, plumber, uglify, watch, watchCoffee;

gulp = require('gulp');

plumber = require('gulp-plumber');

coffee = require('gulp-coffee');

watch = require('gulp-watch');

babel = require("gulp-babel");

uglify = require('gulp-uglify');

Chalk = require('chalk');

coffeeToJs = function(src, dest) {
  console.log("complie " + src);
  if (dest == null) {
    dest = './';
  }
  return gulp.src(src).pipe(plumber()).on('error', console.log).pipe(coffee({
    bare: true
  })).pipe(babel()).pipe(gulp.dest(dest));
};

watchCoffee = function(src, dest) {
  if (dest == null) {
    dest = './';
  }
  return gulp.src(src).pipe(watch(src)).pipe(plumber()).on('error', console.log).pipe(coffee({
    bare: true
  })).pipe(babel()).pipe(gulp.dest(dest));
};

gulp.task('selfWatch', function() {
  var restart;
  restart = function() {
    console.log(Chalk.green.bold('gulpfile changed and restarted'));
    return coffeeToJs('./gulpfile.coffee');
  };
  return watch('./gulpfile.coffee', restart).on('error', function(e) {
    return console.log(Chalk.red.blod(e.message));
  });
});

gulp.task('default', function() {
  gulp.start('web');
  return gulp.start('selfWatch');
});

gulp.task('web', function() {
  var browserSync;
  browserSync = require('browser-sync').create();
  return browserSync.init(null, {
    server: {
      baseDir: "./"
    },
    browser: "ff",
    port: 7000
  });
});
